# Generated by Django 2.0.3 on 2018-06-03 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_auto_20180601_1528'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
    ]
